apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    acme.cert-manager.io/http01-ingress-class: "traefik"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - it-tage.h4r.dev
    secretName: it-tage-h4r-dev-tls
  rules:
  - host: it-tage.h4r.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-service
            port:
              number: 80
